# Generated by Django 4.1.7 on 2023-04-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scarps',
            new_name='Scarp',
        ),
    ]
