# Generated by Django 4.1.7 on 2023-04-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_rename_scarps_scarp'),
    ]

    operations = [
        migrations.AddField(
            model_name='scarp',
            name='desc',
            field=models.TextField(default=None),
        ),
    ]
