# Generated by Django 4.1.7 on 2023-04-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_scarp_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scarp',
            name='desc',
            field=models.TextField(default='None'),
        ),
    ]
