# Generated by Django 4.1.7 on 2023-04-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_scarp_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='scarp',
            name='img',
            field=models.CharField(default='img', max_length=30),
        ),
    ]
