# Generated by Django 4.1.7 on 2023-04-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_scarp_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='companynumber',
            new_name='contactnumber',
        ),
    ]
