# Generated by Django 4.1.7 on 2023-05-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_book_alter_feedback_address_alter_feedback_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('img', models.CharField(default='img', max_length=30)),
                ('current_stock', models.IntegerField()),
                ('current_cost', models.CharField(max_length=20)),
            ],
        ),
    ]
