# Generated by Django 4.1.7 on 2023-05-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_scrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scarp',
            name='current_cost',
        ),
        migrations.RemoveField(
            model_name='scarp',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='scarp',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='scarp',
            name='img',
        ),
        migrations.RemoveField(
            model_name='scarp',
            name='name',
        ),
    ]
