# Generated by Django 4.1.7 on 2023-05-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_remove_scarp_current_cost_remove_scarp_current_stock_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scarp',
        ),
    ]
