# Generated by Django 4.1.7 on 2023-05-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_rename_feedback_enquiry_delete_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquiry',
            new_name='Enquirie',
        ),
    ]
