# Generated by Django 4.1.7 on 2023-05-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_alter_enquirie_address_alter_enquirie_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirie',
            name='gst',
            field=models.CharField(editable=False, max_length=15),
        ),
    ]
