# Generated by Django 4.1.7 on 2023-05-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_alter_enquirie_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='desc',
        ),
    ]
