# Generated by Django 4.1.7 on 2023-05-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_alter_scrap_current_cost_alter_scrap_current_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='Add_Stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrap',
            name='Add_cost',
            field=models.IntegerField(default=0),
        ),
    ]
